### ISSUE TITLE
Check for wildcard certificates or not?

### ISSUE THREAD

**Issue by mdavids** [mlichvar/ntske-test#1]
What's your expert opinion, should NTS servers avoid the use of wildcard certificates (and should ntske-test flag a warning if it encounters one) ?

See https://gitlab.com/NTPsec/ntpsec/-/issues/729 for a discussion.

**Comment by mlichvar** [comment]
I don't see a reason why NTS-KE should have different requirements than HTTPS, but I'm not really an expert on TLS.

chrony follows the gnutls default (wildcards allowed).

ntske-test doesn't verify the hostname at all.

**Comment by mdavids** [comment]
Thanks for your reply and just for the record:

> ntske-test doesn't verify the hostname at all.

Ok, but somewhere it is validated:

Fake host:
```
 ./ntske-test -c ntpfool1.time.nl
Testing server ntpfool1.time.nl (94.198.159.15:4460)

TLSv1.3 connection                      (0+0)           FAIL
```

Real host:
```
./ntske-test -c ntppool1.time.nl
Testing server ntppool1.time.nl (94.198.159.15:4460)

TLSv1.3 connection                      (16+848)        PASS
```

**Comment by mlichvar** [comment]
I think that would be the server checking the requested hostname (needed for virtual hosting).

**Comment by mdavids** [comment]
> I think that would be the server checking the requested hostname (needed for virtual hosting).

Good point.
