### ISSUE TITLE
NTS server is showing only max 1 concurrent sessions 

### ISSUE THREAD

**Issue by saurabh082** [mlichvar/ntske-test#2]
On running ntske-test tool in performance mode, my nts server(NTPsec) is showing many failed sessions and max 1 concurrent sessions.. On increasing the threads, failed sessions are getting increased but successful sessions/sec are same.. Could you please help me understand what it represents and is something wrong with my implementation, need your expert opinion.. 

$ ./ntske-test -b mynts.example.net -t 256
Testing server mynts.example.net (54.x.x.x:4460)

93 successful sessions/sec, 0 failed sessions, max 1 concurrent sessions
126 successful sessions/sec, 241 failed sessions, max 1 concurrent sessions
125 successful sessions/sec, 248 failed sessions, max 1 concurrent sessions
129 successful sessions/sec, 248 failed sessions, max 1 concurrent sessions
122 successful sessions/sec, 244 failed sessions, max 1 concurrent sessions
120 successful sessions/sec, 246 failed sessions, max 1 concurrent sessions

**Comment by mlichvar** [comment]
I think that is expected result for ntpsec. It seems to handle one NTS-KE session at a time using one thread.

**Comment by saurabh082** [comment]
Thanks for the information. Is there any alternative to NTPSec where multiple NTS-KE concurrent sessions can be handled? so that successful sessions/sec can be increased without any failed sessions..

**Comment by mlichvar** [comment]
Yes, chrony has that feature and it has two options for optimizing the server NTS-KE performance: `ntsprocesses` and `maxntsconnections`.
